import {
  EmployeeDemo,
  BranchDemo,
  MetricData,
  ValuePropItem,
  SecurityCardItem,
  PricingPlan,
  FaqItem,
} from './types';

export const DEMO_METRICS = {
  ar: [
    {
      id: 'employees',
      label: 'إجمالي الموظفين',
      value: '248',
      subtext: '241 نشط • 7 في إجازة',
      trend: '+12 هذا الشهر',
      badge: 'نشط',
      variant: 'emerald',
    },
    {
      id: 'branches',
      label: 'الفروع التشغيلية',
      value: '4',
      subtext: 'القاهرة، الإسكندرية، الجيزة، المنصورة',
      trend: 'تغطية متكاملة',
      badge: 'مستقر',
      variant: 'lime',
    },
    {
      id: 'users',
      label: 'المستخدمون الداخليون',
      value: '12',
      subtext: '4 مديري نظام • 8 مشرفين',
      trend: 'صلاحيات محددة',
      badge: 'مؤمّن',
      variant: 'slate',
    },
    {
      id: 'records',
      label: 'اكتمال الملفات',
      value: '98.4%',
      subtext: 'جاهزية سجلات العمل',
      trend: 'تحديث فوري',
      badge: 'محدث',
      variant: 'emerald',
    },
  ] as MetricData[],
  en: [
    {
      id: 'employees',
      label: 'Total Employees',
      value: '248',
      subtext: '241 Active • 7 On Leave',
      trend: '+12 this month',
      badge: 'Active',
      variant: 'emerald',
    },
    {
      id: 'branches',
      label: 'Operational Branches',
      value: '4',
      subtext: 'Cairo, Alexandria, Giza, Mansoura',
      trend: 'Full coverage',
      badge: 'Stable',
      variant: 'lime',
    },
    {
      id: 'users',
      label: 'Internal Users',
      value: '12',
      subtext: '4 System Admins • 8 Managers',
      trend: 'Scoped access',
      badge: 'Secured',
      variant: 'slate',
    },
    {
      id: 'records',
      label: 'Profile Completion',
      value: '98.4%',
      subtext: 'Employment record health',
      trend: 'Live sync',
      badge: 'Up to date',
      variant: 'emerald',
    },
  ] as MetricData[],
};

export const DEMO_EMPLOYEES: Record<'ar' | 'en', EmployeeDemo[]> = {
  ar: [
    {
      id: 'EMP-1042',
      name: 'أحمد محمود الشريف',
      role: 'مدير العمليات التشغيلية',
      department: 'الإدارة العامة',
      branch: 'المقر الرئيسي - المعادي',
      status: 'active',
      joinedDate: '15 يناير 2022',
      avatarSeed: 'AS',
    },
    {
      id: 'EMP-1088',
      name: 'مريم طارق العوضي',
      role: 'أخصائية أولى شؤون أفراد',
      department: 'الموارد البشرية',
      branch: 'المقر الرئيسي - المعادي',
      status: 'active',
      joinedDate: '01 مارس 2023',
      avatarSeed: 'MA',
    },
    {
      id: 'EMP-1115',
      name: 'كريم حسن الديب',
      role: 'مدير فرع الإسكندرية',
      department: 'إدارة الفروع',
      branch: 'فرع الإسكندرية - سموحة',
      status: 'active',
      joinedDate: '10 أغسطس 2023',
      avatarSeed: 'KD',
    },
    {
      id: 'EMP-1142',
      name: 'سارة عبد الرحمن كمال',
      role: 'محاسبة تكاليف ومسيرات',
      department: 'الإدارة المالية',
      branch: 'فرع الجيزة - المهندسين',
      status: 'active',
      joinedDate: '05 ديسمبر 2023',
      avatarSeed: 'SK',
    },
    {
      id: 'EMP-1190',
      name: 'عمر نبيل الزاهد',
      role: 'مشرف خدمات لوجستية',
      department: 'العمليات والدعم',
      branch: 'فرع الدلتا - المنصورة',
      status: 'leave',
      joinedDate: '20 مارس 2024',
      avatarSeed: 'OZ',
    },
  ],
  en: [
    {
      id: 'EMP-1042',
      name: 'Ahmed M. El-Sherif',
      role: 'Operations Director',
      department: 'General Management',
      branch: 'HQ - Maadi',
      status: 'active',
      joinedDate: 'Jan 15, 2022',
      avatarSeed: 'AS',
    },
    {
      id: 'EMP-1088',
      name: 'Mariam T. El-Awady',
      role: 'Senior People Specialist',
      department: 'Human Resources',
      branch: 'HQ - Maadi',
      status: 'active',
      joinedDate: 'Mar 01, 2023',
      avatarSeed: 'MA',
    },
    {
      id: 'EMP-1115',
      name: 'Karim H. El-Deeb',
      role: 'Alexandria Branch Manager',
      department: 'Branch Operations',
      branch: 'Alexandria - Smouha',
      status: 'active',
      joinedDate: 'Aug 10, 2023',
      avatarSeed: 'KD',
    },
    {
      id: 'EMP-1142',
      name: 'Sara A. Kamal',
      role: 'Payroll & Cost Accountant',
      department: 'Finance',
      branch: 'Giza - Mohandessin',
      status: 'active',
      joinedDate: 'Dec 05, 2023',
      avatarSeed: 'SK',
    },
    {
      id: 'EMP-1190',
      name: 'Omar N. El-Zahed',
      role: 'Logistics Supervisor',
      department: 'Operations & Support',
      branch: 'Delta - Mansoura',
      status: 'leave',
      joinedDate: 'Mar 20, 2024',
      avatarSeed: 'OZ',
    },
  ],
};

export const DEMO_BRANCHES: Record<'ar' | 'en', BranchDemo[]> = {
  ar: [
    {
      id: 'BR-01',
      name: 'المقر الرئيسي (المعادي)',
      city: 'القاهرة',
      employeeCount: 142,
      manager: 'أحمد محمود الشريف',
      code: 'CAI-HQ',
    },
    {
      id: 'BR-02',
      name: 'فرع الإسكندرية (سموحة)',
      city: 'الإسكندرية',
      employeeCount: 48,
      manager: 'كريم حسن الديب',
      code: 'ALX-01',
    },
    {
      id: 'BR-03',
      name: 'فرع الجيزة (المهندسين)',
      city: 'الجيزة',
      employeeCount: 36,
      manager: 'سارة عبد الرحمن',
      code: 'GZA-01',
    },
    {
      id: 'BR-04',
      name: 'فرع الدلتا (المنصورة)',
      city: 'الدقهلية',
      employeeCount: 22,
      manager: 'عمر نبيل الزاهد',
      code: 'MNZ-01',
    },
  ],
  en: [
    {
      id: 'BR-01',
      name: 'Headquarters (Maadi)',
      city: 'Cairo',
      employeeCount: 142,
      manager: 'Ahmed M. El-Sherif',
      code: 'CAI-HQ',
    },
    {
      id: 'BR-02',
      name: 'Alexandria Branch (Smouha)',
      city: 'Alexandria',
      employeeCount: 48,
      manager: 'Karim H. El-Deeb',
      code: 'ALX-01',
    },
    {
      id: 'BR-03',
      name: 'Giza Branch (Mohandessin)',
      city: 'Giza',
      employeeCount: 36,
      manager: 'Sara A. Kamal',
      code: 'GZA-01',
    },
    {
      id: 'BR-04',
      name: 'Delta Branch (Mansoura)',
      city: 'Dakahlia',
      employeeCount: 22,
      manager: 'Omar N. El-Zahed',
      code: 'MNZ-01',
    },
  ],
};

export const VALUE_PROPOSITIONS: Record<'ar' | 'en', ValuePropItem[]> = {
  ar: [
    {
      number: '01',
      title: 'أبسط',
      description: 'إدارة واضحة بدون تعقيد غير ضروري، صممت للتركيز على ما يهم الشركة.',
    },
    {
      number: '02',
      title: 'أوضح',
      description: 'رؤية شاملة ومباشرة لبيانات شركتك وفروعك وفريقك في واجهة موحدة.',
    },
    {
      number: '03',
      title: 'مرن',
      description: 'يتناسب بسلاسة مع مختلف أحجام وهياكل الشركات وفروعها المتعددة.',
    },
    {
      number: '04',
      title: 'جاهز للنمو',
      description: 'ابدأ بما تحتاجه اليوم وتوسع بثقة مع اتساع نطاق أعمالك وفريقك.',
    },
  ],
  en: [
    {
      number: '01',
      title: 'Simpler',
      description: 'Clear management without unnecessary complexity, focused on what matters.',
    },
    {
      number: '02',
      title: 'Clearer',
      description: 'Complete and direct visibility into your company, branches, and team in one interface.',
    },
    {
      number: '03',
      title: 'Flexible',
      description: 'Adapts seamlessly to different company sizes, organizational structures, and branches.',
    },
    {
      number: '04',
      title: 'Ready to Grow',
      description: 'Start with what you need today and scale confidently as your organization expands.',
    },
  ],
};

export const SECURITY_CARDS: Record<'ar' | 'en', SecurityCardItem[]> = {
  ar: [
    {
      id: 'secure-access',
      title: 'وصول آمن',
      description: 'تسجيل دخول موثوق مع التحقق بخطوتين وحماية مسارات الوصول للحسابات الإدارية.',
      iconName: 'ShieldCheck',
    },
    {
      id: 'structured-roles',
      title: 'صلاحيات منظمة',
      description: 'تحديد دقيق لأدوار المشرفين ومديري الفروع لضمان اطلاع كل مسؤول على نطاقه المخصص.',
      iconName: 'LockKeyhole',
    },
    {
      id: 'private-data',
      title: 'بيانات خاصة بالشركة',
      description: 'عزل تام لسجلات المؤسسة وقواعد معلوماتها عن أي جهات خارجية أو تداخلات.',
      iconName: 'Building2',
    },
    {
      id: 'sensitive-protection',
      title: 'حماية للبيانات الحساسة',
      description: 'سجلات تتبع دقيقة لكافة التعديلات الإدارية وتنزيل الملفات والبيانات الوظيفية.',
      iconName: 'FileCheck2',
    },
  ],
  en: [
    {
      id: 'secure-access',
      title: 'Secure Access',
      description: 'Reliable authentication with 2-step verification safeguarding administrative portals.',
      iconName: 'ShieldCheck',
    },
    {
      id: 'structured-roles',
      title: 'Structured Permissions',
      description: 'Precise role governance for managers and branch leads based on functional scopes.',
      iconName: 'LockKeyhole',
    },
    {
      id: 'private-data',
      title: 'Dedicated Company Data',
      description: 'Complete workspace isolation ensuring your organizational records remain exclusively yours.',
      iconName: 'Building2',
    },
    {
      id: 'sensitive-protection',
      title: 'Protection of Sensitive Records',
      description: 'Comprehensive audit trails tracking administrative changes and file exports with accountability.',
      iconName: 'FileCheck2',
    },
  ],
};

export const PRICING_PLANS: Record<'ar' | 'en', PricingPlan[]> = {
  ar: [
    {
      id: 'starter',
      name: 'Starter',
      target: 'للشركات الصغيرة',
      description: 'الأساس المتين لتنظيم الموظفين وإدارة الفرع الأول بكل وضوح.',
      features: [
        'إدارة حتى فرعين تشغيليين',
        'ملفات الموظفين والبيانات الأساسية',
        'استيراد البيانات المجمعة عبر Excel',
        'مستخدمان إداريان بصلاحيات مخصصة',
        'لوحة معلومات ومؤشرات تشغيلية',
      ],
      ctaText: 'ابدأ الآن',
    },
    {
      id: 'business',
      name: 'Business',
      target: 'للشركات النامية',
      description: 'الخيار الأمثل للشركات المتوسعة ذات الفروع المتعددة والإدارات المتنوعة.',
      isPopular: true,
      features: [
        'إدارة فروع متعددة بلا حدود مصطنعة',
        'سجلات وظيفية متقدمة وتصنيفات الأقسام',
        'أدوار وصلاحيات متعددة المستويات',
        'أدوات استيراد وتحديث البيانات الذكية',
        'تقارير تصدير جاهزة للطباعة والمراجعة',
        'دعم فني مخصص للتهيئة الأولية',
      ],
      ctaText: 'ابدأ الآن',
    },
    {
      id: 'enterprise',
      name: 'Enterprise',
      target: 'للشركات الأكبر',
      description: 'حل شامل للمجموعات والكيانات ذات الهياكل التنظيمية الواسعة والمتفرعة.',
      features: [
        'هياكل تنظيمية متعددة الشركات والكيانات',
        'حوكمة صلاحيات مخصصة بحسب الفروع والمدن',
        'سجلات تدقيق شاملة لكافة الإجراءات الإدارية',
        'قوالب استيراد مخصصة وتكاملات تشغيلية',
        'مدير حساب استشاري وخطة تهيئة للمؤسسة',
      ],
      ctaText: 'تواصل معنا',
    },
  ],
  en: [
    {
      id: 'starter',
      name: 'Starter',
      target: 'For Small Businesses',
      description: 'The solid foundation to organize employees and manage your initial branches cleanly.',
      features: [
        'Management for up to 2 operational branches',
        'Centralized employee profiles & records',
        'Bulk data import via Excel',
        '2 administrative users with scoped roles',
        'Operational dashboard & overview metrics',
      ],
      ctaText: 'Get started',
    },
    {
      id: 'business',
      name: 'Business',
      target: 'For Growing Companies',
      description: 'The ideal solution for expanding organizations with multiple branches and teams.',
      isPopular: true,
      features: [
        'Multi-branch management without artificial caps',
        'Advanced employee records & department groupings',
        'Multi-tiered administrative roles & permissions',
        'Fast Excel data import and validation engine',
        'Structured reports ready for review and audit',
        'Dedicated onboarding support',
      ],
      ctaText: 'Get started',
    },
    {
      id: 'enterprise',
      name: 'Enterprise',
      target: 'For Larger Enterprises',
      description: 'Comprehensive setup for multi-entity groups and complex organizational structures.',
      features: [
        'Multi-company hierarchy & complex org trees',
        'Custom role governance per division and city',
        'Full administrative audit trails and activity logs',
        'Custom import templates and operational workflows',
        'Dedicated account manager & guided rollout',
      ],
      ctaText: 'Contact us',
    },
  ],
};

export const FAQ_ITEMS: Record<'ar' | 'en', FaqItem[]> = {
  ar: [
    {
      id: 'faq-1',
      question: 'هل تناسب المنصة الشركات الصغيرة؟',
      answer:
        'نعم بالتأكيد. صُممت المنصة لتكون مرنة وخالية من التعقيد، بحيث يمكن للشركات الناشئة والصغيرة بدء تنظيم بيانات موظفيها وفروعها في دقائق معدودة دون الحاجة لتدريب مكثف أو إعدادات مرهقة.',
    },
    {
      id: 'faq-2',
      question: 'هل يمكن إدارة أكثر من فرع؟',
      answer:
        'نعم، تتيح المنصة إنشاء هيكل متكامل لفروع شركتك (مثل المقر الرئيسي، فروع المدن، والمكاتب الإقليمية)، مع ربط كل موظف بفرعه وقسمه، وإتاحة إدارة موحدة لكل الفروع أو تعيين مشرفين لكل فرع على حدة.',
    },
    {
      id: 'faq-3',
      question: 'هل يمكن إضافة الموظفين والفروع عبر Excel؟',
      answer:
        'نعم، توفر المنصة أداة استيراد مخصصة لملفات Excel (.xlsx / .csv). يمكنك تحميل قالب البيانات الجاهز وتعبئة أسماء الموظفين وفروعهم وبياناتهم الوظيفية، ليقوم النظام بالتحقق منها ورفع مئات السجلات بضغطة زر واحدة.',
    },
    {
      id: 'faq-4',
      question: 'هل يمكن استخدام النظام من أكثر من مسؤول؟',
      answer:
        'نعم، يدعم النظام إضافة مستخدمين إداريين متعددين داخل الشركة، مع توزيع الصلاحيات بحسب المسؤولية؛ مثل صلاحية المدير العام، مدير الموارد البشرية، أو مديري الفروع المحددة لضمان السرية والترتيب.',
    },
    {
      id: 'faq-5',
      question: 'هل تدعم المنصة العربية والإنجليزية؟',
      answer:
        'نعم، المنصة مبنية بتصميم يدعم اللغة العربية بشكل أصيل وكامل من اليمين إلى اليسار (RTL)، مع إمكانية التبديل إلى اللغة الإنجليزية (LTR) بسلاسة لتناسب الفرق متعددة الجنسيات.',
    },
    {
      id: 'faq-6',
      question: 'كيف أبدأ؟',
      answer:
        'يمكنك البدء فورًا عبر الضغط على زر "ابدأ الآن"، حيث يمكنك إنشاء مساحة عمل شركتك، إدخال بيانات الفرع الأول، وتجربة استيراد بيانات فريقك بسهولة وسرعة.',
    },
  ],
  en: [
    {
      id: 'faq-1',
      question: 'Is the platform suitable for small businesses?',
      answer:
        'Absolutely. The platform is intentionally built without unnecessary complexity, enabling small businesses and startups to organize employee profiles and branch structures in minutes without lengthy onboarding.',
    },
    {
      id: 'faq-2',
      question: 'Can I manage multiple branches?',
      answer:
        'Yes. You can configure full branch hierarchies (headquarters, regional offices, retail hubs), link every team member to their respective branch and department, and assign scoped permissions to branch leads.',
    },
    {
      id: 'faq-3',
      question: 'Can employees and branches be imported via Excel?',
      answer:
        'Yes. The platform includes a dedicated Excel (.xlsx / .csv) bulk import workflow. Download the ready-to-use template, fill in your employee and branch details, and the validation engine imports hundreds of records cleanly.',
    },
    {
      id: 'faq-4',
      question: 'Can multiple administrators access the system?',
      answer:
        'Yes. You can invite multiple administrative users with granular permission controls tailored to their roles — such as General Manager, HR Lead, or Regional Branch Supervisor.',
    },
    {
      id: 'faq-5',
      question: 'Does the platform support both Arabic and English?',
      answer:
        'Yes. The platform is designed RTL-first for Arabic and fully supports English (LTR) with effortless switching to accommodate multinational and regional teams.',
    },
    {
      id: 'faq-6',
      question: 'How do I get started?',
      answer:
        'You can get started immediately by clicking "Get started", setting up your company workspace, configuring your first branch, and exploring the bulk employee import.',
    },
  ],
};

export const UI_TEXT = {
  ar: {
    announcement: 'إدارة موارد شركتك وموظفيك بطريقة أبسط',
    brandName: 'Lumina HR',
    brandSubtitle: 'Enterprise',
    tagline: 'منصة إدارة الموارد البشرية والمؤسسية',
    navHome: 'الرئيسية',
    navPlatform: 'المنصة',
    navPricing: 'الباقات',
    navFaq: 'الأسئلة الشائعة',
    navLogin: 'تسجيل الدخول',
    ctaPrimary: 'ابدأ الآن',
    ctaExplore: 'استكشف المنصة',
    heroEyebrow: 'منصة إدارة الموارد المؤسسية للشركات',
    heroH1: 'إدارة شركتك وفريقك،\nبطريقة أبسط.',
    heroDescription:
      'منصة حديثة تساعدك على تنظيم شركتك وموظفيك من مكان واحد، بتجربة واضحة ومصممة للنمو.',
    heroMicrocopy: 'إعداد فوري وسلس • مصمم للشركات في مصر والشرق الأوسط • بدون تعقيدات',
    demoNotice: 'بيانات تجريبية للمعاينة فقط',
    credibilityTitle: 'مصمم للشركات التي تبحث عن إدارة أكثر وضوحًا وتنظيمًا',
    credibilityItems: [
      { id: '1', title: 'إدارة منظمة', desc: 'هيكل متين للشركات والفروع' },
      { id: '2', title: 'تجربة بسيطة', desc: 'واجهة واضحة تخلو من التعقيد' },
      { id: '3', title: 'وصول منظم', desc: 'صلاحيات إدارية منضبطة' },
      { id: '4', title: 'مصمم للنمو', desc: 'يتوسع بثبات مع توسع أعمالك' },
    ],
    valuePropEyebrow: 'القيمة الجوهرية',
    valuePropHeadline: 'مصمم ليتناسب مع طريقة عمل شركتك.',
    valuePropSubtitle: 'حلول عملية تمنح فريق الإدارة راحة البال والتحكم الكامل في السجلات التشغيلية.',
    workspaceEyebrow: 'مساحة العمل الإدارية',
    workspaceHeadline: 'مساحة عمل واحدة لشركتك.',
    workspaceDesc:
      'اجمع بيانات المقر الرئيسي وفروعك في لوحة قيادة موحدة تمنحك رؤية فورية لأعداد الموظفين وتوزيعهم دون تشتت بين ملفات متفرقة.',
    workspacePoints: [
      'بطاقة تعريفية موحدة للشركة وفروعها',
      'متابعة لحظية لتوزيع الموظفين والأقسام',
      'إجراءات سريعة لإضافة الفروع والمشرفين',
    ],
    teamEyebrow: 'إدارة الموظفين',
    teamHeadline: 'نظّم فريقك بدون تعقيد.',
    teamDesc:
      'سجلات تفصيلية لكل فرد في المؤسسة تشمل بيانات التعيين والفرع التابع له والقسم والمسؤوليات، مع سهولة البحث والتصفية.',
    teamPoints: [
      'ملف موظف شامل ومنظم',
      'تصفية سريعة حسب الفرع أو الحالة',
      'سجل زمني لبيانات العمل وتاريخ الانضمام',
    ],
    orgEyebrow: 'الهيكل التنظيمي',
    orgHeadline: 'من هيكل الشركة إلى كل فرد في فريقك.',
    orgDesc:
      'تسلسل إداري واضح يربط الشركة القابضة أو المقر الرئيسي بكافة الفروع التشغيلية وفرق العمل الميدانية والمكتبية.',
    companyHQ: 'المقر الرئيسي (القاهرة)',
    branch1: 'فرع الإسكندرية',
    branch2: 'فرع الجيزة',
    branch3: 'فرع المنصورة',
    teamTech: 'فريق التقنية والتحول',
    teamOps: 'فريق العمليات واللوجستيات',
    teamFinance: 'الإدارة المالية والمحاسبة',
    teamPeople: 'إدارة شؤون الأفراد',
    importEyebrow: 'الاستيراد السريع',
    importHeadline: 'أضف الموظفين والفروع دفعة واحدة.',
    importDesc: 'استورد بياناتك من Excel بطريقة واضحة وسريعة.',
    importFileName: 'employees_q3_records.xlsx',
    importFileSize: '1.4 ميجابايت',
    importTotal: '248 سجل تم التعرف عليها',
    importValid: '245 سجل جاهز للاستيراد المباشر',
    importIssues: '3 تحتاج إلى مراجعة بسيطة',
    importReadyStatus: 'جاهز للاستيراد بنجاح',
    importButtonAction: 'استيراد البيانات الآن',
    importReviewAction: 'معاينة السجلات الـ 3',
    securityEyebrow: 'الأمان والخصوصية',
    securityHeadline: 'بيانات شركتك تستحق عناية خاصة.',
    securitySubtitle: 'معايير مؤسسية راسخة تضمن سرية سجلاتك الإدارية وعزل بياناتك بالكامل.',
    growthEyebrow: 'التطور المستمر',
    growthHeadline: 'منصة تنمو مع شركتك.',
    growthSubtitle: 'أساس متين وموثوق اليوم، مع مسار واضح يلبي طموحاتك الإدارية المستقبلية.',
    todayStage: 'اليوم (الأساس المتين)',
    todayBadge: 'متاح بالكامل',
    todayItems: [
      'هيكل الشركة وسجلاتها الرسمية',
      'ملفات الموظفين والتصنيفات',
      'إدارة الفروع التشغيلية والمواقع',
      'المستخدمون الداخليون والصلاحيات',
      'مساحة العمل الإدارية الموحدة',
      'الاستيراد والتصدير المجمع عبر Excel',
    ],
    futureStage: 'مع نمو احتياجاتك',
    futureBadge: 'في مسار التطوير',
    futureItems: [
      'تتبع الحضور والانصراف الذكي',
      'مسيرات الرواتب المتوافقة مع اللوائح',
      'متابعة الأداء الوظيفي والتقييمات',
      'إدارة الامتثال والوثائق والتأمينات',
      'تكاملات موسعة للمنظومة المؤسسية',
    ],
    pricingEyebrow: 'باقات واضحة',
    pricingHeadline: 'اختر الباقة المناسبة لمرحلة نمو شركتك',
    pricingSubtitle: 'شفافية كاملة لتنظيم فريقك دون تكاليف خفية أو تعقيدات.',
    popularBadge: 'الأكثر ملاءمة للشركات النامية',
    faqEyebrow: 'إجابات واضحة',
    faqHeadline: 'الأسئلة الشائعة',
    faqSubtitle: 'كل ما تحتاج لمعرفته حول بدء تنظيم شركتك وفريقك مع Lumina HR.',
    finalCtaHeadline: 'ابدأ ببناء شركة أكثر تنظيمًا اليوم.',
    finalCtaDesc: 'خطوة واحدة تفصلك عن تنظيم فريقك وفروعك وتوفير ساعات من العمل الإداري المتكرر.',
    footerDesc:
      'منصة حديثة لإدارة هيكل الشركة، الموظفين، الفروع، والمستخدمين للشركات في مصر والشرق الأوسط بطريقة واضحة ومنظمة.',
    footerColPlatform: 'المنصة',
    footerColCompany: 'الشركة',
    footerColLegal: 'الشروط والامتثال',
    footerPrivacy: 'سياسة الخصوصية',
    footerTerms: 'شروط الخدمة',
    footerSecurity: 'أمن البيانات',
    footerContact: 'تواصل مع الدعم',
    footerCopyright: 'جميع الحقوق محفوظة © Lumina HR Enterprise.',
    demoWatermark: 'عرض توضيحي - بيانات تجريبية',
  },
  en: {
    announcement: 'A simpler way to manage your company and employees',
    brandName: 'Lumina HR',
    brandSubtitle: 'Enterprise',
    tagline: 'Enterprise Human Resources & Organization Platform',
    navHome: 'Home',
    navPlatform: 'Platform',
    navPricing: 'Pricing',
    navFaq: 'FAQ',
    navLogin: 'Sign In',
    ctaPrimary: 'Get started',
    ctaExplore: 'Explore platform',
    heroEyebrow: 'Enterprise Organization & Workforce Platform',
    heroH1: 'Manage your company and team,\nmore simply.',
    heroDescription:
      'A modern platform that helps you organize your company and employees from one place, with a clear experience built to grow.',
    heroMicrocopy: 'Fast and seamless onboarding • Built for businesses in Egypt & MENA • No unnecessary clutter',
    demoNotice: 'Demo preview data only',
    credibilityTitle: 'Designed for companies seeking clearer, more structured administration',
    credibilityItems: [
      { id: '1', title: 'Structured Management', desc: 'Solid foundation for companies and branches' },
      { id: '2', title: 'Simpler Experience', desc: 'Clean interface free from needless friction' },
      { id: '3', title: 'Scoped Access', desc: 'Disciplined administrative permissions' },
      { id: '4', title: 'Built to Grow', desc: 'Scales steadily as your organization expands' },
    ],
    valuePropEyebrow: 'Core Value',
    valuePropHeadline: 'Designed to fit how your company works.',
    valuePropSubtitle: 'Practical solutions giving management peace of mind and complete command over operational records.',
    workspaceEyebrow: 'Administrative Workspace',
    workspaceHeadline: 'One unified workspace for your company.',
    workspaceDesc:
      'Bring your headquarters and operational branches into a unified dashboard giving immediate visibility into team distribution without juggling scattered files.',
    workspacePoints: [
      'Unified profile for your company and its branch network',
      'Live headcount visibility and department breakdown',
      'Rapid actions to add locations and assign managers',
    ],
    teamEyebrow: 'Employee Directory',
    teamHeadline: 'Organize your team without complexity.',
    teamDesc:
      'Structured records for every team member including hire dates, assigned branch, department, and duties with instant search and filtering.',
    teamPoints: [
      'Comprehensive and clean employee profiles',
      'Rapid filters by branch or employment status',
      'Chronological tenure timeline and onboarding history',
    ],
    orgEyebrow: 'Organizational Structure',
    orgHeadline: 'From company structure to every person in your team.',
    orgDesc:
      'A transparent chain connecting the parent organization to all branches, operational hubs, and departmental teams.',
    companyHQ: 'Headquarters (Cairo)',
    branch1: 'Alexandria Branch',
    branch2: 'Giza Branch',
    branch3: 'Mansoura Branch',
    teamTech: 'Engineering & Transformation',
    teamOps: 'Operations & Logistics',
    teamFinance: 'Finance & Accounting',
    teamPeople: 'People Operations',
    importEyebrow: 'Bulk Import',
    importHeadline: 'Add employees and branches in one go.',
    importDesc: 'Import your data from Excel in a clear, rapid workflow.',
    importFileName: 'employees_q3_records.xlsx',
    importFileSize: '1.4 MB',
    importTotal: '248 records detected',
    importValid: '245 records verified & ready',
    importIssues: '3 require quick review',
    importReadyStatus: 'Ready for clean import',
    importButtonAction: 'Import records now',
    importReviewAction: 'Inspect 3 flagged items',
    securityEyebrow: 'Security & Privacy',
    securityHeadline: 'Your company data deserves dedicated care.',
    securitySubtitle: 'Robust institutional standards ensuring complete confidentiality and workspace isolation.',
    growthEyebrow: 'Continuous Growth',
    growthHeadline: 'A platform that grows with your company.',
    growthSubtitle: 'A dependable foundation today with a clear horizon meeting your future administrative needs.',
    todayStage: 'Today (Strong Foundation)',
    todayBadge: 'Fully Available',
    todayItems: [
      'Company organization & entity profiles',
      'Employee directory & department tagging',
      'Branch management & location hubs',
      'Internal users & role permissions',
      'Unified administrative workspace',
      'Bulk Excel import & export engine',
    ],
    futureStage: 'As Your Needs Grow',
    futureBadge: 'Roadmap Progression',
    futureItems: [
      'Smart attendance & leave tracking',
      'Compliant payroll calculation runs',
      'Performance reviews & competency cycles',
      'Social insurance & regulatory compliance',
      'Extended enterprise integrations',
    ],
    pricingEyebrow: 'Transparent Plans',
    pricingHeadline: 'Choose the plan tailored to your stage of growth',
    pricingSubtitle: 'Clear terms to organize your team without hidden costs or surprises.',
    popularBadge: 'Most popular for expanding businesses',
    faqEyebrow: 'Clear Answers',
    faqHeadline: 'Frequently Asked Questions',
    faqSubtitle: 'Everything you need to know about getting organized with Lumina HR.',
    finalCtaHeadline: 'Start building a more organized company today.',
    finalCtaDesc: 'One simple step to organize your team and branches, saving hours of recurring administrative work.',
    footerDesc:
      'A modern platform to organize company structures, employees, branches, and internal users for businesses in Egypt and the MENA region.',
    footerColPlatform: 'Platform',
    footerColCompany: 'Company',
    footerColLegal: 'Legal & Compliance',
    footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms of Service',
    footerSecurity: 'Data Security',
    footerContact: 'Contact Support',
    footerCopyright: 'All rights reserved © Lumina HR Enterprise.',
    demoWatermark: 'Product Preview — Demo Data',
  },
};
